float64 z   			 # Distance from front of vehicle
Header  header 		         # header for timestamp, etc.
int16   coor_x			 # bounding box's top left x coordinate
int16   coor_y  		 # bounding box's top left y coordinate
int16   size_x			 # bounding box's width
int16   size_y			 # bounding box's height
uint8 value   #Value of sign
uint8 type    # 0: 'Unknown', 1: 'Speed Limit (MPH)', 2: 'Speed Limit (KPH)', 3: 'Stop', 4: 'Yield', 5: 'No Left Turn', 6: 'No Right Turn', 7: 'Do Not Enter', 8: 'Left Turn Only', 9: 'Right Turn Only', 10: 'Railroad Crossing', 11: 'Crosswalk', 12: 'No Turn On Red', 13: 'No U-Turn', 14: 'One Way (Left)', 15: 'One Way (Right)', 16: 'No Parking', 17: 'Handicap Parking'

